rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/item/ItemResource.java

z {"message":"pid not found (uuid:...)","status":404} na {"message":"pid not found","status":404} 
nový formát dělá problémy v LTP NDK - při importu z LTP od Krameria se nejdřív kontroluje ne/přítomnost daného uuid v Krameriu testem zprávy:
private String PID_NOT_FOUND_MESSAGE = "pid not found";
if(textValue.equalsIgnoreCase(PID_NOT_FOUND_MESSAGE)){
return false;
}else{
throw new BusinessException("Unknown result message from kramerius: " + textValue);
}
Bohužel teď neumíme LTP upravit, aby se kontrola prováděla jinak (podle statusu..).
Importy shlukla idea omylem automaticky.

změna formátu chybové hlášky

---

common/src/main/java/cz/incad/kramerius/security/SecuredFedoraAccessImpl.java
common/src/main/java/cz/incad/kramerius/utils/FedoraUtils.java

Audiodatastreamy mají být chráněné stejně jako velký obrázek nebo OCR. Tato oprava to řeší. 
Až se bude řešit https://github.com/ceskaexpedice/kramerius/issues/109, tak prosím pozor na regrese (ačkoliv si myslím, že AudioProxy servlet to řeší)

API - audio datastreams secured

---

search/src/java/cz/incad/Kramerius/CORSFilter.java
search/web/WEB-INF/web.xml

Na základě těchto hlaviček prohlížeče povolí Cross-origin resource sharing. Umožní to provozovat javascriptového klienta i mimo doménu na které je API.

CORS filter

---

search/src/java/cz/incad/Kramerius/security/userscommands/post/RegisterPublicUser.java

Property mail.from by měla být volitelná, ale po pull requestu #187  bez ní nefunguje registrace nových uživatelů.

Oprava pull reqestu #187

---

search/web/inc/details/thumbs.jsp

Může se stát, že zelený čtvereček se zobrazí i u nepřístupného doumentu. Takový případ je možné vidět zde (jenom dnes, večer to přehodím na zámečky, u kterých se problém nevyskytuje)
http://krameriusndktest.mzk.cz/search/i.jsp?pid=uuid:ed1a5170-e8e4-11e4-b834-005056827e51
Přikládám opravu řešící tento problém (vznikla s pomocí @honza-rychtar).

Zelené čtverečky i u nepřístupného dokumentu

---

rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/FeederSolrAuthorDecorate.java

Maličká oprava dělení autorů v API
původně:
"author":["Smoljak, LadislavCimrman, Jára daSvěrák, ZdeněkDivadlo Járy Cimrmana"]
V poli author jsou všichni autoři zřetězení do jednoho řetězce bez mezer.
správně to má být (a po opravě skutečně je):
"author":["Smoljak, Ladislav", "Cimrman, Jára da", "Svěrák, Zdeněk", "Divadlo Járy Cimrmana"]

api - split authors in array

---

common/src/main/java/cz/incad/kramerius/audio/AudioStreamForwardUtils.java
common/src/main/java/cz/incad/kramerius/audio/AudioStreamId.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/item/ItemResource.java
search/src/java/cz/incad/Kramerius/audio/servlet/AudioProxyServlet.java

V snapshot verzi byly rozbité audiostreamy:
viz http://kramerius.mzk.cz/search/api/v5.0/item/uuid:03c9b89b-868b-4b71-b76e-11098965a732/streams/MP3
Stávalo se to protože request.getPathInfo vracelo při volání přes api NULL. Přikládám opravu.

Opravení audio streamů

---

rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/item/decorators/display/ZoomDecorate.java
search/src/java/cz/incad/Kramerius/AbstractImageServlet.java
search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java
search/web/WEB-INF/web.xml

Servlet, který propouští IIIF požadavky na imageserver, viz specifikace http://iiif.io/api/image/2.0/. Protokol je otevřenou alternativou k dlaždicím Zoomify.
[link na validaci API](http://iiif.io/api/image/validator/results.html?server=http%3A%2F%2Fkrameriustest.mzk.cz%2Fsearch%2Fiiif%2F&prefix=&identifier=uuid%3A891ee7f6-42dc-42ae-8b97-475e30dca18d&version=2.0&level=1&id_squares=on&info_json=on&id_basic=on&id_error_escapedslash=on&id_error_unescaped=on&id_escaped=on&id_error_random=on&region_error_random=on&region_pixels=on&size_region=on&size_error_random=on&size_ch=on&size_wc=on&size_percent=on&rot_error_random=on&quality_error_random=on&format_jpg=on&format_error_random=on&jsonld=on&baseurl_redirect=on&cors=on)
Červené požadavky, které neprochází jsou způsobené neúplnou implementací …

IIIF Image API 2.0 servlet

---

import-cmdtool/src/main/java/com/qbizm/kramerius/imptool/poc/convertor/BaseConvertor.java

Prosím o začlenění těchto změn. Při importu z k3 balíků změny v kódu správně zapisují cestu k jpg souborům v foxml.
Změny v kódu jsou větve if-else větve, které odpovídají true/false nastavení convert.imageServerSuffix.removeFilenameExtensions=true v souboru migration.properties

fix .jpg přípony při importu z k3 formátu

---

build.gradle

V současné době neprochází build z důvodu absence pluginu `com.gradle.build-receipt`. Pomůže tento plugin vyměnit za `com.gradle.build-scan`.
```
FAILURE: Build failed with an exception.
* Where:
Build file '/home/rumanekm/workspace/kramerius/build.gradle' line: 19
* What went wrong:
Plugin [id: 'com.gradle.build-receipt', version: '1.0'] was not found in any of the following sources:
- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (plugin 'com.gradle.build-receipt' has no version '1.0' - see https://plugins.gradle.org/plugin/com.gradle.build-receipt for available versions)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 5.095 secs
```

Oprava buildu

---

build.gradle

V aktuálních buildech Krameria nám začala u všech procesů vyskakovat následující hlášky (a procesy padaly do stavu warning).
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/tomcat/webapps/search/WEB-INF/lib/slf4j-jdk14-1.6.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/tomcat/webapps/search/WEB-INF/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
Sep 05, 2016 12:38:30 PM cz.incad.kramerius.processes.impl.ProcessStarter main
SEVERE: system error file contains errors
cz.incad.kramerius.processes.WarningException: system …
```

Multiple SLF4J bindings v lozích procesů

---

client/src/main/java/cz/incad/kramerius/client/RESTHelper.java
common/src/main/java/cz/incad/kramerius/utils/conf/KConfiguration.java
search/src/java/cz/incad/Kramerius/AbstractImageServlet.java

Zkoušíme Kramerius provozovat v Openshiftu. Daří se nám to, ale museli jsme provést dvě malé modifikace:
1. umožnění konfigurace přes proměnné prostředí. Protože není možné mít v Openshiftu konfigurační direktivu s tečkou, je nutné místo teček používat podtržítko. (viz např. environment sekce Krameria v https://raw.githubusercontent.com/moravianlibrary/s2i-kramerius/master/docker-compose.yml).
2. Openshift používá reverzní proxy HAProxy, která je háklivá na validitu hlaviček. Opravil jsem Last-Modified a Last-Fetched (doplnil pomlčky).

Příprava pro nasazení v Openshiftu

---

indexer/src/cz/incad/kramerius/indexer/ExtendedFields.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/virtualcollection/ClientVirtualCollections.java

Verzia krameria 5.3.6 v klientovi neukazovala virt. zbierky a mali sme problém s indexovaním velkých PDF - pri veľkých PDF súboroch nám padala indexácia na "GC overhead limit exceeded", indexovanie pomocou súborov problém vyriešilo.

Upravy z MZK

---

common/src/main/java/cz/incad/kramerius/virtualcollections/CollectionUtils.java

Odstranil jsem nativní volání Base64 enkodéru, který je součástí až Javy 8.
#442 je ukázka, že:
```
sourceCompatibility = 1.6
targetCompatibility= 1.6
```
pro zpětnou kompatibilitu nestačí, ohlídá to pouze language level (např. mi to nedovolí použít diamond operátor, který je až v Javě 7), ale nezakáže mi to použít metody a třídy z novějších verzí.
Správně nastavené IDE by mělo na použití nového API upozornit.
_______
Stejný problém je, že se na několika v místech používá API z Javy 7, takže Kramerius není možné nyní bezproblémově provozovat na Javě 6. Při jistých akcích to bude vyhazovat chyby  MethodNotFoundException or ClassNotFoundException.
> @pavel-stastny: Podpora a nepodpora javy 1.6 je problematicka. Radi bychom ale bohuzel existuji jeste instance kvuli kterym musime dodrzovat …

Fix NoClassDefFoundError, close ceskaexpedice/kramerius#442

---

mw-process/src/main/java/cz/cas/lib/knav/ApplyMWUtils.java
mw-process/src/main/java/cz/cas/lib/knav/indexer/CollectPidForIndexing.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/info/InfoResource.java
search/src/java/cz/incad/Kramerius/AbstractImageServlet.java
search/src/java/cz/incad/Kramerius/backend/guice/BaseModule.java
search/src/java/cz/incad/Kramerius/imaging/DeepZoomServlet.java
search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java
search/src/java/cz/incad/Kramerius/imaging/ZoomifyServlet.java
search/src/java/labels.properties
search/src/java/labels_cs.properties

To co bylo implementováno  v https://github.com/ceskaexpedice/kramerius/pull/97 se nyní propisuje i do API.
Mírně jsem přepsal kopírování streamu z imageserveru, protože v MZK přepneme imageserver na *https://*. Potřeboval jsem podporu `follow redirect`.
Kromě toho nově chytám *ClientAbortException*, kterou vyhodí Tomcat, když je request cancelled (prohlížečka obrázků se často rozhodne, že už dlaždici nepotřebuje a plevelilo nám to logy).
fixes #491

Zpráva o právech v api/info, TLS pro imageserver, mw fix 

---

common/src/main/java/cz/incad/kramerius/security/impl/criteria/CoverAndContentFilter.java
common/src/main/java/cz/incad/kramerius/security/impl/criteria/CriteriumsLoader.java
common/src/main/java/cz/incad/kramerius/security/res/criteriums
common/src/main/java/cz/incad/kramerius/security/utils/SortingRightsUtils.java
common/src/main/java/cz/knav/pdf/PdfTextUnderImage.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/AbstractFeederDecorator.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/SolrDateDecorate.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/SolrISSNDecorate.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/SolrLanguageDecorate.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/search/SearchResource.java
search/src/java/labels.properties
search/src/java/labels_cs.properties

PR obsahuje čtyři věci:
*Oprava PDF s textovou vrstvou*
Dřívější implementace předpokládala, že textstyle má vždy prefix `font`. Není to tak vždy. Mimo jiné pomlčka nemusí mít definovaný font vůbec.
*SOLR bad request*
Když je položený do API SOLR dotaz se špatnou syntaxí, tak se vracelo 500 i když to ve sktuečnosti byla chyba klienta (zanášelo to logy) - nyní se správně vrací 400.
*Filter obálek knih*
Služba obálky knih chtěli mít možnost z Krameria sklízet obálky a obsahy. Tyto typy stran jsou dle zákona autorsky volné, byl implementován benevolentní filtr, kterým toto zveřejní.
*Datum_str ve /feed/custom*
V API feed/custom nebyly PIDy obohacené o datum vydání. Fixnuto.
(Všechny změny jsou už nasazené v MZK na produkci)

Fix PDF s textovou vrstvou, filtr obálek, datum_str

---

common/src/main/java/cz/incad/kramerius/utils/RESTHelper.java
security-core/src/main/java/cz/incad/kramerius/security/jaas/K4LoginModule.java

Minulý PR umožňoval vyhazovat FailedLoginException pouze je-li se uživatel zkoušel přihlášovat s chybným loginem, tento PR umožňuje vyhazovat výjimku i když se uživatel pokusí přihlásit s chybným heslem. Zároveň odstraní zbytečný výpis těla výjimky v RESTHelper.
@MartinRumanek prosím o revizi.

Login troubleshooting rework and useless code elimination

---

search/build.gradle

Po čistém klonu repozitáře (repozitář musí být čistý, nebo se musí smazat .gradle v adresáři projektu, jinak se chyba neprojeví, gradle clean nestačí) mi na Windows neprocházel build s touto chybou:
```
> Task :search:infofile
Created build file C:\Users\martin.rumanek\workspace\testspace\kramerius\search\build\resources\main\build.properties
> Task :search:processResources FAILED
FAILURE: Build failed with an exception.
* What went wrong:
java.io.IOException: Unable to delete file: C:\Users\martin.rumanek\workspace\testspace\kramerius\search\build\resources\main\build.properties
> Unable to delete file: C:\Users\martin.rumanek\workspace\testspace\kramerius\search\build\resources\main\build.properties
```
Přiložený fix chybu opravuje. Writer je bezpečnější zavřít - buď manuálně, nebo ve …

Fix gradle build - writer properly closed

---

rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/feeder/decorators/FeederSolrPolicyDecorate.java

Původní řešení v případě nenalezení záznamu odesílalo `null` do `SOLRUtils.value()`, kde došlo k vyhození `throw new IllegalArgumentException("element must not be null");`, což komplikovalo určení původu chyby, protože neobsahovalo identifikátor dokumentu.
Úprava vyhazuje výjimku už v `FeederSolrPolicyDecorate` spolu s hodnotou `pid`.

Issue moravianlibrary#223: Provide better error info when document is not present in Solr

---

processes/indexer/src/cz/incad/kramerius/indexer/ExtendedFields.java
processes/indexer/src/cz/incad/kramerius/indexer/date/BiblioModsDateParser.java
processes/indexer/src/cz/incad/kramerius/indexer/date/DateQuintet.java

Update pro parsování a indexaci roku vydání v K7:
* parsování dalších formátů dat vydání, jako např. 198- nebo 190^
* datum_begin a datum_end se indexují z MODS:dateIssued point="start" a MODS:dateIssued point="end"

Date parsing update for K7

---

search/web/terms.jsp

@vlahoda omlouvám se, v JSP zůstal odkaz na odmazanou metodu. Začalo se to projevovat stacktracem při provozu.

Remove UTFSort non-existent method from JSP template

---

common/src/main/java/cz/incad/kramerius/impl/FedoraAccessImpl.java
common/src/main/java/cz/incad/kramerius/statistics/accesslogs/dnnt/DNNTStatisticsAccessLogImpl.java
common/src/main/java/cz/incad/kramerius/utils/DCUtils.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/pdf/AbstractPDFResource.java
rest/src/main/java/cz/incad/kramerius/rest/api/k5/client/pdf/PDFResource.java
search/src/java/cz/incad/Kramerius/imaging/DeepZoomServlet.java
search/src/java/cz/incad/Kramerius/imaging/IiifServlet.java
search/src/java/cz/incad/Kramerius/imaging/PrintPDFServlet.java
search/src/java/cz/incad/Kramerius/imaging/ZoomifyServlet.java

Tento PR řeší chyby, na které jsme narazili při testování merge K5 a DNNT. Většina z nich byly chyby logování přistupů způsobené chybějící synchronizací parsování FOXML elementů v DNNTStatisticsAccessLogImpl a DCUtils a ukázaly se v provozu. A přidal jsem informativnější logování, aby bylo vidět u jakých dokumentů problémy vzníkají a tím bychom mohli opravovat připadné chyby v metadatech.

Fix exceptions while logging of access

---

common/src/main/java/cz/incad/kramerius/security/impl/criteria/BenevolentMovingWall.java
common/src/main/java/cz/incad/kramerius/security/impl/criteria/CoverAndContentFilter.java

Kvůli loggeru v **CoverAndContentFilter.java** a XPathFactory v **BenevolentMovingWall.java** vznikaly chyby při pokusu o serializaci objektů.
```
26-Apr-2021 18:40:47.046 INFO [http-nio-8080-exec-12] org.ehcache.core.internal.resilience.LoggingRobustResilienceStrategy.recovered Ehcache key cz.incad.kramerius.security.impl.http.IsActionAllowedFromRequestCached$CacheKey@cbb2ac14 recovered from
org.ehcache.core.spi.store.StoreAccessException: org.ehcache.spi.serialization.SerializerException: java.io.NotSerializableException: java.util.logging.Logger
at org.ehcache.core.exceptions.StorePassThroughException.handleRuntimeException(StorePassThroughException.java:70)
at org.ehcache.impl.internal.store.offheap.AbstractOffHeapStore.computeWithRetry(AbstractOffHeapStore.java:1109)
at …
```

Fix frequent serialization exceptions

---

common/src/main/java/cz/knav/pdf/PdfTextUnderImage.java

Když je v konfiguraci **pdfQueue.useAlto=true** a v souboru **ALTO chybí nepovinný element Styles**, tak **generování PDF** spadne a **vyhodí výjimku PdfTextUnderImageException**. Lze vyřešit vypnutím ALTA, ale vygeneruje se PDF bez textové horní vrstvy.
Vlevo ALTO bez elementu Styles (spadne), vpravo s elementem Styles (projde)
Pro úspěšné vygenerování PDF i s textovou vrstvou (**pdfQueue.useAlto=true**) je řešením defaultní ignorování chybějícího elementu Styles a dosazení defaultního fontu a jeho velikosti (již v kódu).
Kdo by přece jen chtěl, aby při chybějícím elementu Styles a generování PDF s ALTEM házelo chyby přidá do **configuration.properties**:
```
pdfQueue.ignoreMissingSizeAndStyle=false
```

Issue ceskaexpedice#597: adding option to ignore missing info about fonts - style and size

---

indexer/src/cz/incad/kramerius/indexer/SolrOperations.java

Při indexaci vícestránkového PDF a nastavení **indexer.continueOnError=true** se přeskočí chybová stránka a pokračuje se s indexací další stránky.
Odstranění jednoho rozmezí problémových znaků. U nás KNAV jsme po tomhle odstranění nenarazili na žádný problém.

Issue ceskaexpedice#889: indexing multipage pdf

---

shared/common/src/main/java/cz/incad/kramerius/resourceindex/ProcessingIndexRebuild.java

Stará implementácia procesu RebuildProcesingIndex využívala na každých milión prejdených FOXML súborov približne 400 MB heap-u. Nová implementácia funguje na konštantom vyťažení pamäte, nezáleží na tom koľko súborov musí prejsť.
Vo funkcionalite sú dva rozdiely. Stará implementácia vedela detekovať symlink cykly a vedela sa na nich nezacykliť. Nová implementácia toto nevie, ale myslím, že je úplne zbytočné aby to vedela. Druhý rozdiel je, že keď som už implementoval FileVisitor, tak som ho naimplementoval tak, aby na permission denied chybách nepadal, ale aby ich iba zalogoval.
Tu je výstup z JProfiler-u po prejdení 40 miliónov FOXML. (Ku koncu sa garbage collector začal správať trošku inak ako väčšinu behu, a nevykresľuje to najlepšie také dlhé časové úseky. Ale využitie pamäte bolo …

Optimalizácia K7 procesu RebuildProcessingIndex
